first_app/config/routes.rb
Rails.application.routes.draw do
  
  resources :barages_info
  root 'barages_info#index'

end

first_app/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

first_app/app/controllers/barages_info_controller.rb
class BaragesInfoController < ApplicationController

	def order_tab
		@array.each do |k|
			if k.include? "French"
				@new_hash["French"] += 2
			elsif (k.include? "TEPitech") || (k.include? "E-Toeic")
				@new_hash[k] = @new_hash.delete("TEPitech")
				@new_hash[k] = 1;
			elsif k.include? "SQL"
				@new_hash["SQL"] = 1
			elsif k.include? "Conf"
				@new_hash["Conf"] = 1
			else k.include? "Network individual tests"
				@new_hash["Reseaux"] = 1
			end
		end
	end

	def parsejson
		@data_hash.each do |key, value|
			if key['modules']
				value.each do |k, v|
					if (k['codemodule'].include? "B-PRO") && (k['title'].include? "French")
						@array << k['title']
					elsif (k['codemodule'].include? "G-EPI") && (k['grade'] == 'Acquis') && (k['title'].include? "Conf")
						@array << k['title']
					elsif (k['codemodule'].include? "B-BDD") && (k['title'].include? "SQL Individual tests") && (k['grade'] != "Echec") && (k['grade'] != "-")
						@array << k['title']
					elsif (k['codemodule'].include? "B-NET") && (k['title'].include? "Network individual tests") && (k['grade'] != "Echec") && (k['grade'] != "-")
						@array << k['title']
					end
				end
			elsif key['notes']
				value.each do |k, v|
					if (k['codemodule'].include? "B-BDD") && (k['final_note'] >= 15) && (k['titlemodule'].include? "SQL Individual tests")
						@array << k['title']
					elsif (k['codemodule'].include? "B-NET") && (k['final_note'] >= 15) && (k['title'].include? "Exam")
						@array << k['title']
					elsif (k['codemodule'].include? "B-ANG") && (((k['final_note'] >= 750) && ((k['titlemodule'].include? "750") || (k['titlemodule'].include? "TEPitech"))) || ((k['final_note'] >= 550) && ((k['titlemodule'].include? "550") || (k['titlemodule'].include? "TEPitech"))) || ((k['final_note'] >= 650) && ((k['titlemodule'].include? "650") || (k['titlemodule'].include? "TEPitech"))))
						if k['scolaryear'] == @yearS
							@array << k['titlemodule']
						end
					end
				end
			end
		end
		order_tab
	end

	def getjson
		login= "ballot_g"
		@yearS = 2015
		cookies = "curl/cookie.txt"
		url = "https://intra.epitech.eu/user/#{login}/notes/?format=json"
		result = `curl -b #{cookies} #{url}`

		@data_hash = JSON.parse(result, opts = {})
	end

	def index
		@array = []
		@new_hash = Hash["Conf" => 0, "SQL" => 0, "Reseaux" => 0, "French" => 0, "TEPitech" => 0]

		getjson
		parsejson
	end

end

first_app/app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

first_app/app/helpers/application_helper.rb
module ApplicationHelper
end

first_app/app/helpers/barages_info_helper.rb
module BaragesInfoHelper
end

first_app/app/helpers/welcome_helper.rb
module WelcomeHelper
end

first_app/app/views/barages_info/index.html.erb
<h1>Index Html</h1>

<div class="container">
	<table class="table">
		<thead>
			<tr>
				<th>Conf</th>
				<th>Sql</th>
				<th>Reseau</th>
				<th>Expression</th>
				<th>Toeic</th>
			</tr>
		</thead>
		<tbody>
			<tr>
			<% @new_hash.each do | tag, elem | %>
			  	<% if elem == 1 || elem >= 4 %>
			  		<td class="success"><%= tag %></td>
			  	<% else %>
			  		<td class="danger"><%= tag %></td>
			  	<% end %>
			<% end %>
		</tr>
		</tbody>
	</table>
</div>

first_app/app/views/barages_info/new.html.erb
<h1>Hello baragesInfo new</h1>

<%= form_for :get_login, url: barages_info_new_path do |f| %>
	<p>
		<%= f.label :'http://epitech.eu/user/' %>
		<%= f.text_field :login, :size => '4', :maxlength => '8' %>
		/?format=json
	</p>
	<p> 
		<%= f.submit %>
	</p>
<% end %>

<% if @lookuprow %>
	
<% end %>

first_app/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>FirstApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

first_app/app/views/welcome/index.html.erb
<h1>Welcome to my homepage !</h1>